package com.assetops.enums;
public enum NotificationType {
    REQUEST_SUBMITTED, REQUEST_APPROVED, REQUEST_REJECTED, REQUEST_ALLOCATED,
    ASSET_ASSIGNED, ASSET_RETURNED, EOL_WARNING, LICENSE_EXPIRY, MAINTENANCE_ALERT
}
