databases:
  - name: assetops-db
    plan: free

services:

  # 2. Spring Boot Backend
  - type: web
    name: assetops-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    healthCheckPath: /api/actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        fromDatabase:
          name: assetops-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: assetops-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: assetops-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: assetops-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: assetops-db
          property: password
      - key: SPRING_REDIS_URL
        sync: false
      - key: KAFKA_BOOTSTRAP_SERVERS
        sync: false
      - key: KAFKA_SASL_JAAS_CONFIG
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        sync: false
